### ISSUE TITLE
More colors to consider

### ISSUE THREAD

**Issue by timmwille** [ASKnetCommunity/ASKnet-Design#1]
In the past ASKnet grew out of many events and "products" that came in various shapes and colors to name a few that definitely are based on a design theme:

- Open Learning Guide (OLG)
- Open Hardware Guide (OHG)
- Open Training Guide (OTG)
- Open Documentation Guide (ODG)

Currently the Colors of the Website, Directory and Training Page are based on the Open Documentation Guide.

This is good for now, in general the Guides most used in Field where the OLG and OHG  and @yara89 is currently updating the documentation in GitHub to each one of them as good as possible.

So in the future it might be good to also include a darker tone of the orange or into brown and see if parts of the OLG and OHG colors work. Not urgent

**Comment by MartinSchott** [comment]
Yes, I think it is important to add a darker orange/brown color. On LEAD, Links are in the orange, and even when on white background the color is too light. So I created (quickly and without knowing too much about color compatibility, color palettes etc.) this color: #A46131 . It should be checked by someone with more experience though.

**Comment by MartinSchott** [comment]
I am also wondering if the main orange → ![grafik](https://user-images.githubusercontent.com/8080649/150160750-004e9faf-07b5-45dd-bd3e-111563a1a2a2.png) is too bright for screens. I think it could have it's saturation reduced a bit, as colors which are too bright can be exhausting for the eyes. Or it should be used only in small(er) design elements and not as background color → we would need a new orange/beige background color. 
Maybe the bright color works better for printed designs, where the colors originated.

**Comment by yara89** [comment]
@MartinSchott I guess it would depend on how much contrast there is (that's always important, to have a lot of contrast between background and body text color) if you want to take for example someone color blind into consideration, you have to probably do more, but thats a first step ..
@timmwille 
I could make a md file with all the colors if that helps?  ( - the open training guide, i'll add later while I am working on it?) 
the Open Hardware guide moves to another color scheme I feel (also open training guide..?) where it's more bright colors and the OLG and ODG have the earthy colors used on the sites so far...(i like them more, especially for a website) ... 

not sure it's useful for what we need, but I always find this site useful : https://coolors.co/

for color picking and palettes etc...

**Comment by MartinSchott** [comment]
> not sure it's useful for what we need, but I always find this site useful : https://coolors.co/

Thats really cool! I was thinking about something like that. This https://color.adobe.com/de/create/color-wheel and this https://paletton.com are also nice. 

If the Open Hardware guide is even more bright I would personally argue to not take it's colors and rather stay with the earthy ones.

**Comment by timmwille** [comment]
as we're now into 2 releases and a new redesign, I think we can close this issue
